# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hou', '0002_auto_20180622_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
